In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pickle
import numpy as np

## Load data

In [50]:
fp = open("coop_navi_test_2.pkl", "rb")
data = pickle.load(fp)
agent1 = pickle.load(fp)
agent2 = pickle.load(fp)
agent3 = pickle.load(fp)

## Debug data

In [51]:
print("Number of episodes:", len(data))
print("Something something:", len(data[0]))
print("First episode length:", len(data[0][0]))
print("Number of agents:", len(data[0][0][0]))
print("Performance data items:", len(data[0][0][0][0]))

Number of episodes: 4001
Something something: 1
First episode length: 24
Number of agents: 3
Performance data items: 4


In [52]:
print("Episode lengths:")
[len(data[i][0]) for i in range(15)]

Episode lengths:


[24, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25]

In [53]:
print("Performance data (reward, collisions, min_dists, occupied_landmarks):")
[data[i][0][-1][0] for i in range(15)]

Performance data (reward, collisions, min_dists, occupied_landmarks):


[(-1.398971013032809, 1, 0.398971013032809, 1),
 (-1.2704639577251478, 1, 0.27046395772514775, 1),
 (-1.1844202393924324, 1, 0.18442023939243246, 3),
 (-1.3247311887996032, 1, 0.3247311887996031, 1),
 (-1.4137752011065765, 1, 0.4137752011065766, 1),
 (-1.1497638750999932, 1, 0.14976387509999325, 3),
 (-1.177113531619953, 1, 0.17711353161995308, 2),
 (-1.6040079017109763, 1, 0.6040079017109763, 1),
 (-1.324380115226227, 1, 0.32438011522622695, 1),
 (-1.1719803714668693, 1, 0.17198037146686918, 3),
 (-1.2853065925039449, 1, 0.28530659250394486, 2),
 (-1.2150797472690786, 1, 0.21507974726907858, 3),
 (-1.2132708770514253, 1, 0.21327087705142542, 2),
 (-1.2109654127199327, 1, 0.21096541271993266, 3),
 (-1.199468113693102, 1, 0.19946811369310202, 3)]

In [54]:
print("Number of steps:", len(agent1))
print("Number of datas per step", len(agent1[0]))

Number of steps: 100025
Number of datas per step 5


In [55]:
print("State:", agent1[0][0])
print("Action:", agent1[0][1])
print("Reward:", agent1[0][2])
print("Next state:", agent1[0][3])
print("Done:", agent1[0][4])

State: [ 0.          0.          0.9448366   0.81041042 -0.54388864 -1.71701537
 -0.45176729 -1.62840284 -1.65661207 -0.5335673  -1.8086971  -1.52109112
 -1.46952064 -0.5171732   0.          0.          0.          0.        ]
Action: [3.3950317e-05 3.7543112e-05 4.5126571e-06 2.2656102e-06 9.9992168e-01]
Reward: -3.682998410517898
Next state: [ 1.65152269e-05 -4.99959707e-01  9.44838248e-01  7.60414453e-01
 -5.43890295e-01 -1.66701940e+00 -4.51768942e-01 -1.57840687e+00
 -1.65661372e+00 -4.83571326e-01 -1.75869972e+00 -1.47109581e+00
 -1.51608864e+00 -4.70174631e-01  0.00000000e+00  0.00000000e+00
  0.00000000e+00  0.00000000e+00]
Done: 0.0


## Convert states

In [56]:
states1 = np.array([agent1[i][0] for i in range(len(agent1))]).reshape((-1, 25, len(agent1[0][0])))
states2 = np.array([agent2[i][0] for i in range(len(agent2))]).reshape((-1, 25, len(agent2[0][0])))
states3 = np.array([agent3[i][0] for i in range(len(agent3))]).reshape((-1, 25, len(agent3[0][0])))
print("State shapes:", states1.shape, states2.shape, states3.shape)

State shapes: (4001, 25, 18) (4001, 25, 18) (4001, 25, 18)


## Convert actions

In [57]:
actions1 = np.array([agent1[i][1] for i in range(len(agent1))]).reshape((-1, 25, len(agent1[0][1])))
actions2 = np.array([agent2[i][1] for i in range(len(agent2))]).reshape((-1, 25, len(agent2[0][1])))
actions3 = np.array([agent3[i][1] for i in range(len(agent3))]).reshape((-1, 25, len(agent3[0][1])))
print("Action shapes:", actions1.shape, actions2.shape, actions3.shape)

Action shapes: (4001, 25, 5) (4001, 25, 5) (4001, 25, 5)


## Convert rewards

In [58]:
rewards1 = np.array([agent1[i][2] for i in range(len(agent1))]).reshape((-1, 25))
rewards2 = np.array([agent2[i][2] for i in range(len(agent2))]).reshape((-1, 25))
rewards3 = np.array([agent3[i][2] for i in range(len(agent3))]).reshape((-1, 25))
print("Reward shapes:", rewards1.shape, rewards2.shape, rewards3.shape)

Reward shapes: (4001, 25) (4001, 25) (4001, 25)


## Convert collisions

In [59]:
collisions1 = np.array([data[i][0][-1][0][1] for i in range(len(data))])
collisions2 = np.array([data[i][0][-1][1][1] for i in range(len(data))])
collisions3 = np.array([data[i][0][-1][2][1] for i in range(len(data))])
print("Collisions shapes:", collisions1.shape, collisions2.shape, collisions3.shape)

Collisions shapes: (4001,) (4001,) (4001,)


## Debug collisions

In [60]:
np.where(collisions1 != collisions2)

(array([  53,  256,  665,  868, 1114, 1143, 1213, 1516, 1666, 2075, 2258,
        2486, 2614, 2751, 2771, 3489, 3528, 3673, 3687, 3713]),)

In [61]:
np.where(collisions2 != collisions3)

(array([  53,  682, 1122, 1304, 1516, 1638, 2312, 2477, 2634, 2664, 2765,
        2834, 3235, 3238, 3528, 3713, 3903, 3967]),)

In [62]:
np.where(collisions1 != collisions3)

(array([ 256,  665,  682,  868, 1114, 1122, 1143, 1213, 1304, 1638, 1666,
        2075, 2258, 2312, 2477, 2486, 2614, 2634, 2664, 2751, 2765, 2771,
        2834, 3235, 3238, 3489, 3673, 3687, 3903, 3967]),)

Conclusion - collisions are tracked separately for each agent. Collisions happen in pairs.

## Convert occupied

In [63]:
occupied1 = np.array([data[i][0][-1][0][3] for i in range(len(data))])
occupied2 = np.array([data[i][0][-1][1][3] for i in range(len(data))])
occupied3 = np.array([data[i][0][-1][2][3] for i in range(len(data))])
print("Occupied shape:", occupied1.shape, occupied2.shape, occupied3.shape)

Occupied shape: (4001,) (4001,) (4001,)


## Debug occupied 

In [64]:
print(np.sum(occupied1 != occupied2))
print(np.sum(occupied2 != occupied3))

0
0


Conclusion - occupied is common over all agents.

In [65]:
print("Number of episodes, where:")
print("- all landmarks are covered", np.sum(occupied1 == 3))
print("- at least 2 landmarks covered", np.sum(occupied1 >= 2))
print("- at least 1 landmark covered", np.sum(occupied1 >= 1))
print("- zero landmarks covered", np.sum(occupied1 == 0))

Number of episodes, where:
- all landmarks are covered 1213
- at least 2 landmarks covered 2824
- at least 1 landmark covered 3817
- zero landmarks covered 184


## Convert landmarks occupied by agent

In [66]:
# calculate distance of each agent from each landmark
landmarks1 = np.sqrt(np.sum(states1[:,-1,4:10].reshape((states1.shape[0], 3, 2))**2, axis=-1))
landmarks2 = np.sqrt(np.sum(states2[:,-1,4:10].reshape((states2.shape[0], 3, 2))**2, axis=-1))
landmarks3 = np.sqrt(np.sum(states3[:,-1,4:10].reshape((states3.shape[0], 3, 2))**2, axis=-1))
print("Landmarks shapes:", landmarks1.shape, landmarks2.shape, landmarks3.shape)

Landmarks shapes: (4001, 3) (4001, 3) (4001, 3)


## Debug landmark occupation

In [67]:
print("Agent1 covers some landmark:", np.sum(np.sum(landmarks1 < 0.1, axis=-1) > 0))
print("Agent2 covers some landmark:", np.sum(np.sum(landmarks2 < 0.1, axis=-1) > 0))
print("Agent3 covers some landmark:", np.sum(np.sum(landmarks3 < 0.1, axis=-1) > 0))

Agent1 covers some landmark: 2910
Agent2 covers some landmark: 1796
Agent3 covers some landmark: 3118


Curious why agent2 performs so bad... Maybe because it's in the middle? With random positioning that shouldn't be a problem.

In [68]:
print("Agent1 covers more than one landmark:", np.sum(np.sum(landmarks1 < 0.1, axis=-1) > 1))
print("Agent2 covers more than one landmark:", np.sum(np.sum(landmarks2 < 0.1, axis=-1) > 1))
print("Agent3 covers more than one landmark:", np.sum(np.sum(landmarks3 < 0.1, axis=-1) > 1))

Agent1 covers more than one landmark: 4
Agent2 covers more than one landmark: 5
Agent3 covers more than one landmark: 21


In [69]:
occupied = np.logical_or(np.logical_or(landmarks1 < 0.1, landmarks2 < 0.1), landmarks3 < 0.1)
all_occupied = np.all(occupied, axis=-1)
print("Occupied from landmarks:", np.sum(all_occupied))
print("Occupied from perf data:", np.sum(occupied1 == 3))
print("All occupations match:", np.all(all_occupied == (occupied1 == 3)))

Occupied from landmarks: 1213
Occupied from perf data: 1213
All occupations match: True


Our landmark data matches the performance data. Can use landmark data further on.

## Create target values

In [70]:
y1 = landmarks1 < 0.1
y2 = landmarks2 < 0.1
y3 = landmarks3 < 0.1
print("Target shapes:", y1.shape, y2.shape, y3.shape)

Target shapes: (4001, 3) (4001, 3) (4001, 3)


In [71]:
print("Agent1 covered counts:", np.histogram(np.sum(y1, axis=-1), [0, 1, 2, 3, 4])[0])
print("Agent2 covered counts:", np.histogram(np.sum(y2, axis=-1), [0, 1, 2, 3, 4])[0])
print("Agent3 covered counts:", np.histogram(np.sum(y3, axis=-1), [0, 1, 2, 3, 4])[0])

Agent1 covered counts: [1091 2906    4    0]
Agent2 covered counts: [2205 1791    5    0]
Agent3 covered counts: [ 883 3097   21    0]


## Load policy

In [72]:
from train import parse_args, make_env, get_trainers
import maddpg.common.tf_util as U
import tensorflow as tf

In [74]:
arglist = parse_args(['--benchmark', '--deterministic'])

tf.reset_default_graph()
tf.InteractiveSession().as_default()

# Create environment
env = make_env('simple_spread', arglist, arglist.benchmark)
# Create agent trainers
obs_shape_n = [env.observation_space[i].shape for i in range(env.n)]
num_adversaries = min(env.n, arglist.num_adversaries)
trainers = get_trainers(env, num_adversaries, obs_shape_n, arglist)
print('Using good policy {} and adv policy {}'.format(arglist.good_policy, arglist.adv_policy))

# Initialize
U.initialize()

print('Loading previous state...')
U.load_state('coop_navi_2/policy')

Using good policy maddpg and adv policy maddpg
Loading previous state...
INFO:tensorflow:Restoring parameters from coop_navi_2/policy


## Debug policy

In [75]:
actions = trainers[0].act(states1[0])
print("Predicted actions match saved actions:", np.allclose(actions1[0], actions))

Predicted actions match saved actions: True


## Extract hidden states

In [76]:
h1_values = trainers[0].p_debug['h1_values']
h2_values = trainers[0].p_debug['h2_values']

X1_h1 = np.array([h1_values(states1[i]) for i in range(states1.shape[0])])
X1_h2 = np.array([h2_values(states1[i]) for i in range(states1.shape[0])])

print("Agent1 hidden state shapes:", X1_h1.shape, X1_h2.shape)

h1_values = trainers[1].p_debug['h1_values']
h2_values = trainers[1].p_debug['h2_values']

X2_h1 = np.array([h1_values(states2[i]) for i in range(states2.shape[0])])
X2_h2 = np.array([h2_values(states2[i]) for i in range(states2.shape[0])])

print("Agent2 hidden state shapes:", X1_h1.shape, X1_h2.shape)

h1_values = trainers[2].p_debug['h1_values']
h2_values = trainers[2].p_debug['h2_values']

X3_h1 = np.array([h1_values(states3[i]) for i in range(states3.shape[0])])
X3_h2 = np.array([h2_values(states3[i]) for i in range(states3.shape[0])])

print("Agent3 hidden state shapes:", X1_h1.shape, X1_h2.shape)

Agent1 hidden state shapes: (4001, 25, 64) (4001, 25, 64)
Agent2 hidden state shapes: (4001, 25, 64) (4001, 25, 64)
Agent3 hidden state shapes: (4001, 25, 64) (4001, 25, 64)


## Save dataset

In [79]:
np.savez_compressed("data.npz",
    X1_obs=states1, 
    X1_h1=X1_h1, 
    X1_h2=X1_h2,
    X1_act=actions1,
    X2_obs=states2, 
    X2_h1=X2_h1, 
    X2_h2=X2_h2,
    X2_act=actions2,
    X3_obs=states3, 
    X3_h1=X3_h1, 
    X3_h2=X3_h2,
    X3_act=actions3,
    y1=y1,
    y2=y2,
    y3=y3,
)