In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import pickle
import numpy as np

## Load data

In [3]:
fp = open("coop_navi_128units4real_test_3a.pkl", "rb")
data = pickle.load(fp)
agent1 = pickle.load(fp)
agent2 = pickle.load(fp)
agent3 = pickle.load(fp)

## Debug data

In [4]:
print("Number of episodes:", len(data))
print("Something something:", len(data[0]))
print("First episode length:", len(data[0][0]))
print("Number of agents:", len(data[0][0][0]))
print("Performance data items:", len(data[0][0][0][0]))

Number of episodes: 4000
Something something: 1
First episode length: 25
Number of agents: 3
Performance data items: 4


In [5]:
print("Episode lengths:")
[len(data[i][0]) for i in range(15)]

Episode lengths:


[25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25, 25]

In [6]:
print("Performance data (reward, collisions, min_dists, occupied_landmarks):")
[data[i][0][-1][0] for i in range(15)]

Performance data (reward, collisions, min_dists, occupied_landmarks):


[(-1.3654919031820483, 1, 0.3654919031820483, 2),
 (-1.329316183760786, 1, 0.32931618376078603, 1),
 (-1.2699935108702554, 1, 0.2699935108702554, 2),
 (-1.2364959755356626, 1, 0.23649597553566248, 3),
 (-1.2824834630685653, 1, 0.2824834630685652, 2),
 (-1.266229279989877, 1, 0.2662292799898771, 2),
 (-1.755712221145904, 1, 0.755712221145904, 1),
 (-1.243874810880896, 1, 0.24387481088089585, 3),
 (-1.1145911359386769, 1, 0.11459113593867691, 3),
 (-1.1330878114019052, 1, 0.13308781140190526, 3),
 (-1.2260246046969931, 1, 0.22602460469699315, 2),
 (-1.2439373507098532, 1, 0.24393735070985315, 2),
 (-1.2461263348180451, 1, 0.24612633481804502, 3),
 (-1.3106623353800457, 1, 0.3106623353800457, 1),
 (-1.4756746241572074, 1, 0.4756746241572075, 1)]

In [7]:
print("Number of steps:", len(agent1))
print("Number of datas per step", len(agent1[0]))

Number of steps: 100000
Number of datas per step 5


In [8]:
print("State:", agent1[0][0])
print("Action:", agent1[0][1])
print("Reward:", agent1[0][2])
print("Next state:", agent1[0][3])
print("Done:", agent1[0][4])

State: [ 0.          0.         -0.04992221  0.23009745  0.94681212 -1.19442627
 -0.15955518 -0.13012089  0.80592057 -1.10582529  0.07249372  0.48442981
  0.20845996 -0.05406745  0.          0.          0.          0.        ]
Action: [1.1770740e-08 1.0069446e-05 4.9464877e-08 1.3934602e-08 9.9998987e-01]
Reward: -3.5186466462319896
Next state: [-0.81931066 -0.28749222 -0.13185327  0.20134823  1.02874318 -1.16567705
 -0.07762411 -0.10137167  0.88785163 -1.07707607  0.10612246  0.51154567
  0.40478029 -0.0625853   0.          0.          0.          0.        ]
Done: 0.0


## Convert states

In [9]:
states1 = np.array([agent1[i][0] for i in range(len(agent1))]).reshape((-1, 25, len(agent1[0][0])))
states2 = np.array([agent2[i][0] for i in range(len(agent2))]).reshape((-1, 25, len(agent2[0][0])))
states3 = np.array([agent3[i][0] for i in range(len(agent3))]).reshape((-1, 25, len(agent3[0][0])))
print("State shapes:", states1.shape, states2.shape, states3.shape)

State shapes: (4000, 25, 18) (4000, 25, 18) (4000, 25, 18)


## Convert actions

In [10]:
actions1 = np.array([agent1[i][1] for i in range(len(agent1))]).reshape((-1, 25, len(agent1[0][1])))
actions2 = np.array([agent2[i][1] for i in range(len(agent2))]).reshape((-1, 25, len(agent2[0][1])))
actions3 = np.array([agent3[i][1] for i in range(len(agent3))]).reshape((-1, 25, len(agent3[0][1])))
print("Action shapes:", actions1.shape, actions2.shape, actions3.shape)

Action shapes: (4000, 25, 5) (4000, 25, 5) (4000, 25, 5)


## Convert rewards

In [11]:
rewards1 = np.array([agent1[i][2] for i in range(len(agent1))]).reshape((-1, 25))
rewards2 = np.array([agent2[i][2] for i in range(len(agent2))]).reshape((-1, 25))
rewards3 = np.array([agent3[i][2] for i in range(len(agent3))]).reshape((-1, 25))
print("Reward shapes:", rewards1.shape, rewards2.shape, rewards3.shape)

Reward shapes: (4000, 25) (4000, 25) (4000, 25)


## Convert collisions

In [12]:
# subtract one, because by default collision with agent itself is also counted
collisions1 = np.array([[data[i][0][t][0][1] for t in range(len(data[i][0]))] for i in range(len(data))]) - 1
collisions2 = np.array([[data[i][0][t][1][1] for t in range(len(data[i][0]))] for i in range(len(data))]) - 1
collisions3 = np.array([[data[i][0][t][2][1] for t in range(len(data[i][0]))] for i in range(len(data))]) - 1
print("Collisions shapes:", collisions1.shape, collisions2.shape, collisions3.shape)

Collisions shapes: (4000, 25) (4000, 25) (4000, 25)


## Debug collisions

In [13]:
np.where(np.sum(collisions1, axis=-1) != np.sum(collisions2, axis=-1))

(array([   1,    3,    4,    6,   27,   29,   30,   35,   57,   59,   65,
          69,   74,   81,   85,   91,   92,   94,  126,  127,  131,  137,
         150,  152,  158,  161,  171,  175,  178,  180,  197,  203,  210,
         214,  216,  220,  224,  236,  246,  250,  251,  254,  284,  299,
         311,  327,  338,  345,  348,  351,  362,  365,  367,  368,  372,
         374,  384,  385,  390,  392,  420,  421,  423,  432,  434,  458,
         461,  462,  463,  464,  468,  473,  493,  496,  498,  503,  504,
         507,  508,  519,  529,  538,  541,  561,  562,  575,  578,  579,
         587,  593,  598,  599,  600,  611,  630,  651,  657,  658,  665,
         667,  681,  693,  694,  700,  705,  722,  724,  735,  745,  759,
         785,  787,  791,  792,  793,  796,  797,  808,  823,  829,  835,
         859,  860,  865,  876,  891,  904,  906,  956,  960,  961,  964,
         983,  984,  995,  998, 1007, 1020, 1042, 1050, 1059, 1063, 1065,
        1066, 1071, 1076, 1079, 1087, 

In [14]:
np.where(np.sum(collisions2, axis=-1) != np.sum(collisions3, axis=-1))

(array([   6,   24,   26,   27,   29,   30,   32,   50,   56,   57,   59,
          65,   67,   69,   74,   77,   81,   85,   91,   92,   93,  114,
         117,  126,  127,  137,  149,  158,  161,  164,  183,  193,  197,
         207,  210,  214,  220,  231,  236,  238,  240,  244,  246,  249,
         254,  267,  280,  282,  284,  294,  299,  311,  314,  323,  327,
         335,  345,  346,  348,  351,  362,  365,  368,  372,  373,  375,
         390,  412,  414,  419,  420,  421,  424,  434,  449,  473,  477,
         493,  495,  503,  504,  506,  508,  514,  515,  519,  536,  538,
         554,  561,  578,  581,  594,  602,  611,  628,  660,  667,  685,
         687,  693,  707,  708,  716,  719,  720,  721,  745,  773,  784,
         791,  793,  797,  799,  808,  821,  822,  829,  860,  861,  865,
         869,  881,  891,  904,  905,  906,  928,  940,  942,  944,  947,
         961,  969,  982, 1002, 1004, 1020, 1027, 1030, 1042, 1049, 1050,
        1059, 1065, 1066, 1079, 1087, 

In [15]:
np.where(np.sum(collisions1, axis=-1) != np.sum(collisions3, axis=-1))

(array([   1,    3,    4,   24,   26,   32,   35,   50,   56,   65,   67,
          77,   91,   93,   94,  114,  117,  126,  131,  149,  150,  152,
         164,  171,  175,  178,  180,  183,  193,  203,  207,  216,  224,
         231,  238,  240,  244,  249,  250,  251,  267,  280,  282,  294,
         314,  323,  335,  338,  346,  367,  373,  374,  375,  384,  385,
         392,  412,  414,  419,  423,  424,  432,  449,  458,  461,  462,
         463,  464,  468,  473,  477,  495,  496,  498,  506,  507,  508,
         514,  515,  529,  536,  538,  541,  554,  562,  575,  579,  581,
         587,  593,  594,  598,  599,  600,  602,  628,  630,  651,  657,
         658,  660,  665,  681,  685,  687,  694,  700,  705,  707,  708,
         716,  719,  720,  721,  722,  724,  735,  759,  773,  784,  785,
         787,  792,  796,  799,  821,  822,  823,  835,  859,  861,  869,
         876,  881,  905,  928,  940,  942,  944,  947,  956,  960,  964,
         969,  982,  983,  984,  995, 

Conclusion - collisions are tracked separately for each agent. Collisions happen in pairs.

## Mean collisions per episode

In [16]:
print("Histogram of simulatenous number of collisions:")
np.histogram(collisions1 + collisions2 + collisions3, bins=[0, 1, 2, 3, 4, 5, 6])

Histogram of simulatenous number of collisions:


(array([98299,     0,  1696,     0,     5,     0]),
 array([0, 1, 2, 3, 4, 5, 6]))

In [17]:
print("Histogram of collisions per episode:")
np.histogram(np.sum((collisions1 + collisions2 + collisions3)/2, axis=-1), bins=range(23))

Histogram of collisions per episode:


(array([3205,  332,  304,   58,   40,   21,   16,    6,    6,    1,    4,
           1,    2,    2,    0,    1,    1,    0,    0,    0,    0,    0]),
 array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
        17, 18, 19, 20, 21, 22]))

In [18]:
# divide sum of collisions by 2, because every collision is counted twice
# sum collisions per episode and take mean over episodes
print("Mean number of collisions per episode:", np.mean(np.sum((collisions1 + collisions2 + collisions3) / 2, axis=-1)))

Mean number of collisions per episode: 0.4265


## Convert occupied

In [19]:
occupied1 = np.array([data[i][0][-1][0][3] for i in range(len(data))])
occupied2 = np.array([data[i][0][-1][1][3] for i in range(len(data))])
occupied3 = np.array([data[i][0][-1][2][3] for i in range(len(data))])
print("Occupied shape:", occupied1.shape, occupied2.shape, occupied3.shape)

Occupied shape: (4000,) (4000,) (4000,)


## Debug occupied 

In [20]:
print(np.sum(occupied1 != occupied2))
print(np.sum(occupied2 != occupied3))

0
0


Conclusion - occupied is common over all agents.

In [21]:
print("Number of episodes, where:")
print("- all landmarks are covered", np.sum(occupied1 == 3))
print("- at least 2 landmarks covered", np.sum(occupied1 >= 2))
print("- at least 1 landmark covered", np.sum(occupied1 >= 1))
print("- zero landmarks covered", np.sum(occupied1 == 0))

Number of episodes, where:
- all landmarks are covered 2337
- at least 2 landmarks covered 3551
- at least 1 landmark covered 3939
- zero landmarks covered 61


## Convert landmarks occupied by agent

In [22]:
new_states1 = np.array([agent1[i][3] for i in range(len(agent1))]).reshape((-1, 25, len(agent1[0][3])))
new_states2 = np.array([agent2[i][3] for i in range(len(agent2))]).reshape((-1, 25, len(agent2[0][3])))
new_states3 = np.array([agent3[i][3] for i in range(len(agent3))]).reshape((-1, 25, len(agent3[0][3])))
print("New state shapes:", states1.shape, states2.shape, states3.shape)

New state shapes: (4000, 25, 18) (4000, 25, 18) (4000, 25, 18)


In [23]:
# calculate distance of each agent from each landmark
landmarks1 = np.sqrt(np.sum(new_states1[:,-1,4:10].reshape((new_states1.shape[0], 3, 2))**2, axis=-1))
landmarks2 = np.sqrt(np.sum(new_states2[:,-1,4:10].reshape((new_states2.shape[0], 3, 2))**2, axis=-1))
landmarks3 = np.sqrt(np.sum(new_states3[:,-1,4:10].reshape((new_states3.shape[0], 3, 2))**2, axis=-1))
print("Landmarks shapes:", landmarks1.shape, landmarks2.shape, landmarks3.shape)

Landmarks shapes: (4000, 3) (4000, 3) (4000, 3)


## Debug landmark occupation

In [24]:
print("Agent1 covers some landmark:", np.sum(np.sum(landmarks1 < 0.1, axis=-1) > 0))
print("Agent2 covers some landmark:", np.sum(np.sum(landmarks2 < 0.1, axis=-1) > 0))
print("Agent3 covers some landmark:", np.sum(np.sum(landmarks3 < 0.1, axis=-1) > 0))

Agent1 covers some landmark: 3421
Agent2 covers some landmark: 3421
Agent3 covers some landmark: 2964


In [25]:
print("Agent1 covers more than one landmark:", np.sum(np.sum(landmarks1 < 0.1, axis=-1) > 1))
print("Agent2 covers more than one landmark:", np.sum(np.sum(landmarks2 < 0.1, axis=-1) > 1))
print("Agent3 covers more than one landmark:", np.sum(np.sum(landmarks3 < 0.1, axis=-1) > 1))

Agent1 covers more than one landmark: 10
Agent2 covers more than one landmark: 9
Agent3 covers more than one landmark: 2


In [26]:
occupied = np.logical_or(np.logical_or(landmarks1 < 0.1, landmarks2 < 0.1), landmarks3 < 0.1)
all_occupied = np.all(occupied, axis=-1)
print("All occupied from landmarks:", np.sum(all_occupied))
print("All occupied from perf data:", np.sum(occupied1 == 3))
print("All occupations match:", np.all(all_occupied == (occupied1 == 3)))

All occupied from landmarks: 2337
All occupied from perf data: 2337
All occupations match: True


Our landmark data matches the performance data. Can use landmark data further on.

## Mean distance from landmark

In [27]:
print("Average agent distance from the closest landmark at the end:", 
      np.mean(np.min(np.stack([landmarks1, landmarks2, landmarks3]), axis=-1)))

Average agent distance from the closest landmark at the end: 0.07030050909155913


In [28]:
print("Average agent distance from all landmarks at the end:", np.mean(np.concatenate([landmarks1, landmarks2, landmarks3])))

Average agent distance from all landmarks at the end: 0.7267458741249332


In [29]:
all_landmarks1 = np.sqrt(np.sum(new_states1[:,:,4:10].reshape((states1.shape[0], states1.shape[1], 3, 2))**2, axis=-1))
all_landmarks2 = np.sqrt(np.sum(new_states2[:,:,4:10].reshape((states2.shape[0], states1.shape[1], 3, 2))**2, axis=-1))
all_landmarks3 = np.sqrt(np.sum(new_states3[:,:,4:10].reshape((states3.shape[0], states1.shape[1], 3, 2))**2, axis=-1))

In [30]:
print("Average agent distance from the closest landmark over episode:", 
      np.mean(np.min(np.stack([all_landmarks1, all_landmarks2, all_landmarks3]), axis=-1)))

Average agent distance from the closest landmark over episode: 0.22048922354350506


In [31]:
print("Average agent distance from all landmarks over episode:", np.mean(np.concatenate([all_landmarks1, all_landmarks2, all_landmarks3])))

Average agent distance from all landmarks over episode: 0.7833622721433872


In [32]:
print("Mean sum of min distances from each landmark to agents:", np.mean(np.array(data)[:, :, -1, :, 2]))

Mean sum of min distances from each landmark to agents: 0.19972429675059744


In [33]:
print("The same thing calculated from landmark data", 
      np.mean(np.sum(np.min(np.stack([landmarks1, landmarks2, landmarks3]), axis=0), axis=1)))

The same thing calculated from landmark data 0.19972429675059744


Conclusion - it's not clear how average distance is calculated in Table 2. All numbers I'm getting are substantially below 1.767 they get.

## Create target values

In [34]:
y1 = landmarks1 < 0.1
y2 = landmarks2 < 0.1
y3 = landmarks3 < 0.1
print("Target shapes:", y1.shape, y2.shape, y3.shape)

Target shapes: (4000, 3) (4000, 3) (4000, 3)


In [35]:
print("Agent1 covered counts by landmark:", np.sum(y1, axis=0))
print("Agent2 covered counts by landmark:", np.sum(y2, axis=0))
print("Agent3 covered counts by landmark:", np.sum(y3, axis=0))

Agent1 covered counts by landmark: [1410   14 2007]
Agent2 covered counts by landmark: [  11 2120 1299]
Agent3 covered counts by landmark: [1890 1070    6]


In [36]:
idx = (occupied1 == 3)
print("When all three landmarks are covered")
print("Agent1 covered counts by landmark:", np.sum(y1[idx], axis=0))
print("Agent2 covered counts by landmark:", np.sum(y2[idx], axis=0))
print("Agent3 covered counts by landmark:", np.sum(y3[idx], axis=0))

When all three landmarks are covered
Agent1 covered counts by landmark: [ 723    2 1613]
Agent2 covered counts by landmark: [   4 1616  722]
Agent3 covered counts by landmark: [1610  719    2]


In [37]:
print("Agent1 covered counts:", np.histogram(np.sum(y1, axis=-1), [0, 1, 2, 3, 4])[0])
print("Agent2 covered counts:", np.histogram(np.sum(y2, axis=-1), [0, 1, 2, 3, 4])[0])
print("Agent3 covered counts:", np.histogram(np.sum(y3, axis=-1), [0, 1, 2, 3, 4])[0])

Agent1 covered counts: [ 579 3411   10    0]
Agent2 covered counts: [ 579 3412    9    0]
Agent3 covered counts: [1036 2962    2    0]


## Load policy

In [38]:
from train import parse_args, make_env, get_trainers
import maddpg.common.tf_util as U
import tensorflow as tf

In [41]:
arglist = parse_args(['--benchmark', '--deterministic', '--num-units', '128'])

tf.reset_default_graph()
tf.InteractiveSession().as_default()

# Create environment
env = make_env('simple_spread', arglist, arglist.benchmark)
# Create agent trainers
obs_shape_n = [env.observation_space[i].shape for i in range(env.n)]
num_adversaries = min(env.n, arglist.num_adversaries)
trainers = get_trainers(env, num_adversaries, obs_shape_n, arglist)
print('Using good policy {} and adv policy {}'.format(arglist.good_policy, arglist.adv_policy))

# Initialize
U.initialize()

print('Loading previous state...')
U.load_state('coop_navi_128units4real_3/policy')

Using good policy maddpg and adv policy maddpg
Loading previous state...
INFO:tensorflow:Restoring parameters from coop_navi_128units4real_3/policy


## Debug policy

In [42]:
actions = trainers[0].act(states1[0])
print("Predicted actions match saved actions:", np.allclose(actions1[0], actions))
assert np.allclose(actions1[0], actions)

Predicted actions match saved actions: True


## Extract hidden states

In [43]:
h1_values = trainers[0].p_debug['h1_values']
h2_values = trainers[0].p_debug['h2_values']

X1_h1 = np.array([h1_values(states1[i]) for i in range(states1.shape[0])])
X1_h2 = np.array([h2_values(states1[i]) for i in range(states1.shape[0])])

print("Agent1 hidden state shapes:", X1_h1.shape, X1_h2.shape)

h1_values = trainers[1].p_debug['h1_values']
h2_values = trainers[1].p_debug['h2_values']

X2_h1 = np.array([h1_values(states2[i]) for i in range(states2.shape[0])])
X2_h2 = np.array([h2_values(states2[i]) for i in range(states2.shape[0])])

print("Agent2 hidden state shapes:", X1_h1.shape, X1_h2.shape)

h1_values = trainers[2].p_debug['h1_values']
h2_values = trainers[2].p_debug['h2_values']

X3_h1 = np.array([h1_values(states3[i]) for i in range(states3.shape[0])])
X3_h2 = np.array([h2_values(states3[i]) for i in range(states3.shape[0])])

print("Agent3 hidden state shapes:", X1_h1.shape, X1_h2.shape)

Agent1 hidden state shapes: (4000, 25, 128) (4000, 25, 128)
Agent2 hidden state shapes: (4000, 25, 128) (4000, 25, 128)
Agent3 hidden state shapes: (4000, 25, 128) (4000, 25, 128)


## Save dataset

In [44]:
np.savez_compressed("data_128units.npz",
    X1_obs=states1, 
    X1_h1=X1_h1, 
    X1_h2=X1_h2,
    X1_act=actions1,
    X2_obs=states2, 
    X2_h1=X2_h1, 
    X2_h2=X2_h2,
    X2_act=actions2,
    X3_obs=states3, 
    X3_h1=X3_h1, 
    X3_h2=X3_h2,
    X3_act=actions3,
    y1=y1,
    y2=y2,
    y3=y3,
)